name: indexer-create-from-uri

on:
  workflow_dispatch:

jobs:
  create-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: heyitsmemark/create-azure-search-indexer@main
        with:
          azureSearchInstance: plop
          azureSearchAdminKey: ${{ secrets.AZURE_SEARCH_ADMIN_KEY }}
          indexerDefinitionUri: https://plopstorage.blob.core.windows.net/public/indexer.json