name: indexer-create-from-file

on:
  workflow_dispatch:

jobs:
  create-indexer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: heyitsmemark/create-azure-search-indexer@1.0.0
        with:
          azureSearchInstance: plop
          azureSearchAdminKey: ${{ secrets.AZURE_SEARCH_ADMIN_KEY }}
          indexerDefinitionFile: ./test-definitions/indexer.json